apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-java
  name: hello-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-java
    spec:
      containers:
      - image: npalavecino/docker-java:1.0
        name: hello-java
        imagePullPolicy: true
        resources: {}
        ports:
          - containerPort: 8080 
status: {}
