apiVersion: v1
kind: Service
metadata:
  name: hello-java
  labels:
    run: hello-java
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello-java
  type: LoadBalancer
